### ISSUE TITLE
[debops.slapd] Configure TLS certificates failed

### ISSUE THREAD

**Issue by erikschwalbe** [debops/debops#1171]
Ubuntu 18.04.3
ansible (2.9.1)
debops (1.2.0)

added new host "ldap" to debops_service_slapd and run debops with default settings

...
TASK [debops.slapd : Configure TLS certificates] ********************************************************************************************************************************************************************************************************************
task path: /home/ansible/.local/share/debops/debops/ansible/roles/debops.slapd/tasks/slapd_tasks.yml:17
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ldap_attrs_payload_3WWTuV/ansible_ldap_attrs_payload.zip/ansible/modules/ldap_attrs.py", line 399, in main
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 629, in modify_s
    return self.modify_ext_s(dn,modlist,None,None)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 602, in modify_ext_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 749, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 756, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 329, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 313, in _ldap_call
    result = func(*args,**kwargs)
OTHER: {'desc': u'Other (e.g., implementation specific) error'}

fatal: [ldap]: FAILED! => {
    "changed": false,
    "details": "{'desc': u'Other (e.g., implementation specific) error'}",
    "invocation": {
        "module_args": {
            "attributes": {
                "olcTLSCACertificateFile": "/etc/pki/realms/domain/CA.crt",
                "olcTLSCertificateFile": "/etc/pki/realms/domain/default.crt",
                "olcTLSCertificateKeyFile": "/etc/pki/realms/domain/default.key"
            },
            "bind_dn": null,
            "bind_pw": "",
            "dn": "cn=config",
            "ordered": false,
            "params": null,
            "server_uri": "ldapi:///",
            "start_tls": false,
            "state": "exact",
            "validate_certs": true
        }
    },
    "msg": "Attribute action failed."
}

Regards,
Erik

**Comment by drybjed** [comment]
Was the `debops.pki` role, or the common playbook applied on the host? Seems that way, otherwise `debops.slapd` role wouldn't try import the certificates... For some reason `slapd` blocked configuration of TLS, hard to tell why from the output. You should check if there's any clues in system logs, `/var/log/syslog` might tell you something.

**Comment by erikschwalbe** [comment]
Yes the debops.pki and debops.common role was applied on the host.
What output / infos do you need?

**Comment by drybjed** [comment]
Hard to tell. Try this: in one terminal, on the `ldap` host run:
```
journalctl -f -u slapd
```
On the Ansible Controller, run:
```
debops service/slapd -l ldap -t role::slapd:tasks
```
See what OpenLDAP logs tell you when Ansible tasks fail again. You could also increase the logging in `slapd` by setting in the Ansible inventory:
```
slapd__tasks:

  - name: 'Configure the OpenLDAP server log level'
    dn: 'cn=config'
    attributes:
      olcLogLevel: 'stats acl config'
    state: 'exact'
```
You can see possible log levels by running the command:
```
slapd -d ?
```

**Comment by erikschwalbe** [comment]
Ok, thanks for the assistance.
I did all the stuff. But for me there are no strange things in the logfile:
https://pastebin.com/HgSpw3KK

**Comment by drybjed** [comment]
Does that mean that subsequent `debops` runs work fine? Do you still get errors when you try and configure OpenLDAP with Ansible?

You could try to check the logs this way on fresh host to have a clean installation to compare against.

**Comment by erikschwalbe** [comment]
No, debops.slapd role does not work. 
Ansible error log from the first post and the pastebin log were created at the same time.

**Comment by drybjed** [comment]
@erikschwalbe In that case it will be hard to diagnose it over GitHub issues, and most people probably won't be happy when we spam their e-mail accounts that way. :-) Perhaps we could schedule a remote session over the weekend, so I could look at your environment and see what the reason might be? We can talk on IRC about this.

**Comment by erikschwalbe** [comment]
Ok, found the problem after analyzing the syslog. Its an apparmor problem.
`apparmor="DENIED" operation="open" profile="/usr/sbin/slapd" name="/etc/pki/realms/domain/public/intermediate_root.pem" pid=1082 comm="slapd" requeste
d_mask="r" denied_mask="r"`

`apparmor="DENIED" operation="open" profile="/usr/sbin/slapd" name="/etc/pki/realms/domain/private/key.pem" pid=1082 comm="slapd" requested_mask="r" denied_mask="r"`

`apparmor="DENIED" operation="open" profile="/usr/sbin/slapd" name="/etc/pki/dhparam/params/set0/dh3072.pem" pid=1082 comm="slapd" requested_mask="r" d
enied_mask="r"`

Regards,
Erik

**Comment by drybjed** [comment]
Interesting. I suppose then that this makes the `debops-contrib.apparmor` role relevant and it will have to be finally migrated and incorporated in the main project. But that's good, at least we now have an use case for it that can be tested.

For now you should let the `/usr/sbin/slapd` binary have access to these files, then the OpenLDAP service should work fine.

**Comment by paulinsche** [comment]
Duplicate of #456 ?

**Comment by drybjed** [comment]
@paulinsche Yes, looks like it. So, a proper AppArmor support in DebOps is needed. I'll try to add it before `v2.0.0` release, but I'm not sure yet if that will happen. If not, it will most likely land in `v2.1.0`.
