### ISSUE TITLE
owncloud role broken when using postgres

### ISSUE THREAD

**Issue by Cadair** [debops/debops#1428]
I am attempting to run the owncloud role (nexcloud variant) against my postgres database (different host, but happens on same host as well).

I get the following output:

```
< TASK [postgresql : Grant PostgreSQL groups] >

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'DatabaseError' object has no attribute 'message'                                                                                            
failed: [cloud -> database.cadair.com] (item={'roles': ['nextcloud'], 'groups': ['nextcloud'], 'database': 'nextcloud', 'state': 'present'}) => changed=false                                                                                            
  ansible_loop_var: item
  item:
    database: nextcloud
    groups:
    - nextcloud
    roles:
    - nextcloud
    state: present
  module_stderr: |-
    Traceback (most recent call last):
      File "/tmp/ansible_postgresql_privs_payload_1o0e_sdh/ansible_postgresql_privs_payload.zip/ansible/modules/database/postgresql/postgresql_privs.py", line 1046, in main                                                                                  
      File "/tmp/ansible_postgresql_privs_payload_1o0e_sdh/ansible_postgresql_privs_payload.zip/ansible/modules/database/postgresql/postgresql_privs.py", line 750, in manipulate_privs                                                                       
    psycopg2.DatabaseError: role "nextcloud" is a member of role "nextcloud"
  
  
    During handling of the above exception, another exception occurred:
  
    Traceback (most recent call last):
      File "<stdin>", line 102, in <module>
      File "<stdin>", line 94, in _ansiballz_main
      File "<stdin>", line 40, in invoke_module
      File "/usr/lib/python3.7/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_postgresql_privs_payload_1o0e_sdh/ansible_postgresql_privs_payload.zip/ansible/modules/database/postgresql/postgresql_privs.py", line 1065, in <module>                                                                              
      File "/tmp/ansible_postgresql_privs_payload_1o0e_sdh/ansible_postgresql_privs_payload.zip/ansible/modules/database/postgresql/postgresql_privs.py", line 1055, in main                                                                                  
    AttributeError: 'DatabaseError' object has no attribute 'message'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

I am happy to poke into this if someone can give me some hints on debugging it.

**Comment by drybjed** [comment]
First of all, can you specify Ansible version, DebOps version, OS release? That could help narrow it down. This seems to be an issue in the `postgresql_privs` Ansible module.

**Comment by Cadair** [comment]
```
ansible 2.9.6
  config file = /.../ansible.cfg
  configured module search path = [...]                                             
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
```
hosts and controller are debian stable.

**Comment by flohoff** [comment]
I have the same issue - Same ansible 2.9.6, controller Debian/10, Host Ubuntu 18.04

I solved it by:

owncloud__postgresql__dependent_groups: []

**Comment by l00ptr** [comment]
I have done some test and indeed without the solution proposed by @flohoff the owncloud role don't work for nextcloud with PostgreSQL.

FYI:
``` console
 $ debops --version
debops 3.0.5
```
and
``` console
$ ansible --version
ansible [core 2.15.1]
  config file = /xxxx/ansible.cfg
  configured module search path = ['/xxxx/ansible/plugins/modules', '/xxxx/.venv/lib/python3.11/site-packages/debops/_data/ansible/collections/ansible_collections/debops/debops/plugins/modules', '/home/xx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /xxxx/.venv/lib/python3.11/site-packages/ansible
  ansible collection location = /xxxx/ansible/collections:/xxx/.ansible/collections:/xxxx/.venv/lib/python3.11/site-packages/debops/_data/ansible/collections:/usr/share/ansible/collections
  executable location = /xxxx/.venv/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/xxxx/.venv/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```
