### ISSUE TITLE
[system_users] Operation not permitted as dependency

### ISSUE THREAD

**Issue by apapsch** [debops/debops#1553]
A custom role includes system_users as dependency:

```
dependencies:
  - role: system_users
```

The dependent variable gets set via fancy expression:

```
system_users__dependent_accounts: >-
  {%- set accounts = [] -%}
  {%- for exporter in prom_exporters__exporters -%}
    {{
    accounts.append({
      'name': exporter.name,
      'group': exporter.name,
      'system': True,
      'shell': '/bin/false',
      'home': '/',
      'create_home': False
    })
    }}
  {%- endfor -%}
  {{ accounts }}
```

Independently of the custom role, inventory groups set `system_users__group_accounts`. Those accounts are already created on the tested host.

Running the custom role results in error when it comes to configuring SSH keys for one of the already created accounts:

```
[...]
TASK [system_users : Configure SSH authorized keys for system users] *****************************************************************************************************************
task path: /home/ep/.local/lib/python3.8/site-packages/debops/ansible/roles/system_users/tasks/main.yml:217
[...]
redirecting (type: modules) ansible.builtin.authorized_key to ansible.posix.authorized_key
Using module file /home/xx/.local/lib/python3.8/site-packages/ansible_collections/ansible/posix/plugins/modules/authorized_key.py
Pipelining is enabled.
<xxx.foo.bar> ESTABLISH SSH CONNECTION FOR USER: None
<xxx.foo.bar> SSH: EXEC ssh -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=30m -4 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/xx/.ansible/cp/81334e9891 xxx.foo.bar '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''                                                                                                                                                 
<xxx.foo.bar> (1, b'', b'Traceback (most recent call last):\n  File "<stdin>", line 102, in <module>\n  File "<stdin>", line 94, in _ansiballz_main\n  File "<stdin>", line 40, in invoke_module\n  File "/usr/lib/python2.7/runpy.py", line 188, in run_module\n    fname, loader, pkg_name)\n  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code\n    exec code in run_globals\n  File "/tmp/ansible_authorized_key_payload_zZG0O0/ansible_authorized_key_payload.zip/ansible_collections/ansible/posix/plugins/modules/authorized_key.py", line 668, in <module>\n  File "/tmp/ansible_authorized_key_payload_zZG0O0/ansible_authorized_key_payload.zip/ansible_collections/ansible/posix/plugins/modules/authorized_key.py", line 663, in main\n  File "/tmp/ansible_authorized_key_payload_zZG0O0/ansible_authorized_key_payload.zip/ansible_collections/ansible/posix/plugins/modules/authorized_key.py", line 626, in enforce_state\n  File "/tmp/ansible_authorized_key_payload_zZG0O0/ansible_authorized_key_payload.zip/ansible_collections/ansible/posix/plugins/modules/authorized_key.py", line 336, in keyfile\nOSError: [Errno 1] Operation not permitted: \'/home/xx/.ssh\'\n')                                                                                                                                                                   
<xxx.foo.bar> Failed to connect to the host via ssh: Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_authorized_key_payload_zZG0O0/ansible_authorized_key_payload.zip/ansible_collections/ansible/posix/plugins/modules/authorized_key.py", line 668, in <module>
  File "/tmp/ansible_authorized_key_payload_zZG0O0/ansible_authorized_key_payload.zip/ansible_collections/ansible/posix/plugins/modules/authorized_key.py", line 663, in main
  File "/tmp/ansible_authorized_key_payload_zZG0O0/ansible_authorized_key_payload.zip/ansible_collections/ansible/posix/plugins/modules/authorized_key.py", line 626, in enforce_state
  File "/tmp/ansible_authorized_key_payload_zZG0O0/ansible_authorized_key_payload.zip/ansible_collections/ansible/posix/plugins/modules/authorized_key.py", line 336, in keyfile
OSError: [Errno 1] Operation not permitted: '/home/xx/.ssh'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_authorized_key_payload_zZG0O0/ansible_authorized_key_payload.zip/ansible_collections/ansible/posix/plugins/modules/authorized_key.py", line 668, in <module>
  File "/tmp/ansible_authorized_key_payload_zZG0O0/ansible_authorized_key_payload.zip/ansible_collections/ansible/posix/plugins/modules/authorized_key.py", line 663, in main
  File "/tmp/ansible_authorized_key_payload_zZG0O0/ansible_authorized_key_payload.zip/ansible_collections/ansible/posix/plugins/modules/authorized_key.py", line 626, in enforce_state
  File "/tmp/ansible_authorized_key_payload_zZG0O0/ansible_authorized_key_payload.zip/ansible_collections/ansible/posix/plugins/modules/authorized_key.py", line 336, in keyfile
OSError: [Errno 1] Operation not permitted: '/home/xx/.ssh'
failed: [xxx] (item={'name': 'xx', 'state': 'present', 'sshkeys': ['ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDEoNMnMRhISexxxxxxx xx']}) => {                                                                                                                                                                          
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "admin": true,
        "comment": "XXX",
        "id": 70,
        "name": "xx",
        "real_weight": 70,
        "separator": false,
        "shell": "/bin/bash",
        "sshkeys": [
            "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDEoNMnMRhISexxxxxxx xx"
        ],
        "state": "present",
        "weight": 0
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_authorized_key_payload_zZG0O0/ansible_authorized_key_payload.zip/ansible_collections/ansible/posix/plugins/modules/authorized_key.py\", line 668, in <module>\n  File \"/tmp/ansible_authorized_key_payload_zZG0O0/ansible_authorized_key_payload.zip/ansible_collections/ansible/posix/plugins/modules/authorized_key.py\", line 663, in main\n  File \"/tmp/ansible_authorized_key_payload_zZG0O0/ansible_authorized_key_payload.zip/ansible_collections/ansible/posix/plugins/modules/authorized_key.py\", line 626, in enforce_state\n  File \"/tmp/ansible_authorized_key_payload_zZG0O0/ansible_authorized_key_payload.zip/ansible_collections/ansible/posix/plugins/modules/authorized_key.py\", line 336, in keyfile\nOSError: [Errno 1] Operation not permitted: '/home/xx/.ssh'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

This might have to do with https://github.com/ansible/ansible/issues/22562, though I haven't digged further than that. While that issue is closed, it doesn't seem to be solved:

> It turns out this problem is also true for the target of include_role (with or without apply: {become: true}) or import_role inside a first-order dependency role, so my options for getting tasks in deep dependencies to run as the correct user are quickly becoming limited.

followed by

> Closing this per [an earlier comment that acknowledged having abandoned the problem]

This seems to effectively neuter the possibility to use debops roles as dependencies, or am I missing something?

**Comment by apapsch** [comment]
> It turns out this problem is also true for the target of include_role (with or without apply: {become: true}) or import_role inside a first-order dependency role, so my options for getting tasks in deep dependencies to run as the correct user are quickly becoming limited.

Seems I shot too fast, adding:

```
- import_role:
    name: system_users
  become: yes
```

has the role execute successfully. Though I'm not sure calling it like that is desired.

**Comment by drybjed** [comment]
First of all - i never advocated the use of `users` and `system_users` roles as dependencies for other roles - they are there so that you can define user accounts in the Ansible inventory without the need to write custom roles. If you are actually writing a role, you should use the Ansible modules `group`, `user`, `authorized_key` (in this case) to handle the required UNIX accounts and SSH keys. It's pure economics - using 3 tasks in your role vs how many tasks the `users`, `system_users` roles have right now.

Now, as for this particular error... Since you probably are running the playbook with `become: True`, the tasks are executed as the `root` account. The "OSError: [Errno 1] Operation not permitted: '/home/xx/.ssh'\n" error suggests some issue in the target filesystem...

And now I see that you found the reason the role did not execute successfully. Well, the `system_users` role is meant to be run with `root` privileges since it manages the UNIX accounts, groups and so on. Most of the DebOps playbooks and roles are written with `root` account in mind, and the `become: True` parameter is set on the playbook level. If you write your own playbooks, you need to add that as well.

**Comment by apapsch** [comment]
Thanks for the clarification! I'll go with invoking the Ansible modules then.

> The "OSError: [Errno 1] Operation not permitted: '/home/xx/.ssh'\n" error suggests some issue in the target filesystem...

That was my first though as well, though it turned out playbook level `become: True` was missing. My (wrong) expectation was that roles become root themselves, if necessary for them.

You added the documentation tag. I could assimilate your general remarks into a new section of https://docs.debops.org/en/master/user-guide/playbooks.html and the system_users specific remarks in https://docs.debops.org/en/master/ansible/roles/system_users/getting-started.html#example-playbook.

The latter page mentions "If you are using this role without DebOps". I always understood that as meaning a playbook including  Debops via Ansible Galaxy, i.e. not invoking `debops custom-playbook`, where custom-playbook is integrated into the structure created by `debops-init`.

**Comment by apapsch** [comment]
I haven't used debops in a while, closing.
