### ISSUE TITLE
Debops Padlock cannot take more than one receipient.

### ISSUE THREAD

**Issue by prk0ghy** [debops/debops#1784]
When encrypting debops-padlock with mote than one receipient it will crash with:

```bash

(debops-og) [prk0ghy@dekstop KupferSync-Inventory]$ debops
Mounting '/home/prk0ghy/Repositories/KupferSync-Systems/KupferSync-Inventory/ansible/.encfs.secret' using '/home/prk0ghy/Repositories/KupferSync-Systems/KupferSync-Inventory/ansible/.encfs.secret/padlock'..
Traceback (most recent call last):
  File "/home/prk0ghy/src/venv/debops-og/bin/debops", line 4, in <module>
    __import__('pkg_resources').run_script('debops===2.2.0-763-ga31878532', 'debops')
  File "/home/prk0ghy/src/venv/debops-og/lib/python3.8/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/prk0ghy/src/venv/debops-og/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/home/prk0ghy/src/venv/debops-og/lib/python3.8/site-packages/debops-2.2.0_763_ga31878532-py3.8.egg/EGG-INFO/scripts/debops", line 282, in <module>
  File "/home/prk0ghy/src/venv/debops-og/lib/python3.8/site-packages/debops-2.2.0_763_ga31878532-py3.8.egg/EGG-INFO/scripts/debops", line 269, in main
  File "/home/prk0ghy/src/venv/debops-og/lib/python3.8/site-packages/debops-2.2.0_763_ga31878532-py3.8.egg/debops/__init__.py", line 243, in padlock_unlock
  File "/usr/lib64/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/prk0ghy/Repositories/KupferSync-Systems/KupferSync-Inventory/ansible/.encfs.secret/padlock', '/home/prk0ghy/Repositories/KupferSync-Systems/KupferSync-Inventory/ansible/.encfs.secret', '/home/prk0ghy/Repositories/KupferSync-Systems/KupferSync-Inventory/ansible/secret']' returned non-zero exit status 2.

```

generally i think it is a bad idea to use encfs, we should try to use ansible-vault

**Comment by prk0ghy** [comment]
I think this is some other reason still ansible vault would be nice
