### ISSUE TITLE
Debops 3.0.1: debops.debops.pki: Error "name 'conf_section' is not defined"

### ISSUE THREAD

**Issue by mathieumd** [debops/debops#2036]
I'm trying to upgrade Debops to 3.0.1 (through Ansible Galaxy), but got an error during the PKI role:

```
ansible-playbook site.yml -l test.example.com --diff -t role::pki -vvv
...
TASK [debops.debops.pki : DebOps pre_tasks hook] **********************************************************************************************************************************************
task path: /home/mathieu/dev/ansible/.collections/ansible_collections/debops/debops/roles/pki/tasks/main.yml:21
exception during Jinja2 execution: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/template/__init__.py", line 1015, in _lookup
    ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
  File "/home/mathieu/dev/ansible/.collections/ansible_collections/debops/debops/plugins/lookup/task_src.py", line 163, in run
    if conf_section in config and conf_key in config[conf_section]:
NameError: name 'conf_section' is not defined
fatal: [test.example.com]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'debops.debops.task_src'. Error was a <class 'NameError'>, original message: name 'conf_section' is not defined. name 'conf_section' is not defined"
}
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks/import_playbook instead. This feature will be removed in version 2.16. Deprecation warnings can be disabled by
setting deprecation_warnings=False in ansible.cfg.
```

As it was working with previous version of Debops, my guess is it's a regression.

**Comment by hungpr0** [comment]
It should be the plugin issue https://github.com/debops/debops/pull/2034

**Comment by mathieumd** [comment]
Thanks!
