### ISSUE TITLE
distupgrade from buster to bullseye "connection refused"

### ISSUE THREAD

**Issue by jankowa** [debops/debops#2149]
Just tried to use tools/dist-upgrade for upgrading host from buster to bullseye.

I have to mention that the host is an unprivileged lxc-container, so maybe things are special. The error is hiere:

```
TASK [Send mail with information about the upgrade] **************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ConnectionRefusedError: [Errno 111] Connection refused
fatal: [host.example.org]: FAILED! => changed=false 
  module_stderr: |-
    Shared connection to host.example.org closed.
  module_stdout: |-
    Traceback (most recent call last):
      File "/home/dkn/.ansible/tmp/ansible-tmp-1657127955.6977012-786802-239789109580758/AnsiballZ_mail.py", line 107, in <module>
        _ansiballz_main()
      File "/home/dkn/.ansible/tmp/ansible-tmp-1657127955.6977012-786802-239789109580758/AnsiballZ_mail.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/dkn/.ansible/tmp/ansible-tmp-1657127955.6977012-786802-239789109580758/AnsiballZ_mail.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.mail', init_globals=dict(_module_fqn='ansible_collections.community.general.plugins.modules.mail', _modlib_path=modlib_path),
      File "/usr/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_mail_payload_qbah8igt/ansible_mail_payload.zip/ansible_collections/community/general/plugins/modules/mail.py", line 385, in <module>
      File "/tmp/ansible_mail_payload_qbah8igt/ansible_mail_payload.zip/ansible_collections/community/general/plugins/modules/mail.py", line 270, in main
      File "/usr/lib/python3.9/smtplib.py", line 253, in __init__
        (code, msg) = self.connect(host, port)
      File "/usr/lib/python3.9/smtplib.py", line 339, in connect
        self.sock = self._get_socket(host, port, self.timeout)
      File "/usr/lib/python3.9/smtplib.py", line 310, in _get_socket
        return socket.create_connection((host, port), timeout,
      File "/usr/lib/python3.9/socket.py", line 843, in create_connection
        raise err
      File "/usr/lib/python3.9/socket.py", line 831, in create_connection
        sock.connect(sa)
    ConnectionRefusedError: [Errno 111] Connection refused
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

```

After that ansible seems to be broken. Every other command fails with:

```
TASK [Gathering Facts] *******************************************************************************************************************************
fatal: [host.example.org]: FAILED! => changed=false 
  ansible_facts: {}
  failed_modules:
    ansible.legacy.setup:
      ansible_facts:
        discovered_interpreter_python: /usr/bin/python3
      cmd: /etc/ansible/facts.d/apt.fact
      failed: true
      invocation:
        module_args:
          fact_path: /etc/ansible/facts.d
          filter: []
          gather_subset:
          - all
          gather_timeout: 10
      msg: '[Errno 2] No such file or directory: b''/etc/ansible/facts.d/apt.fact'''
      rc: 2
      stderr: ''
      stderr_lines: []
      stdout: ''
      stdout_lines: []
  msg: |-
    The following modules failed to execute: ansible.legacy.setup

PLAY RECAP *******************************************************************************************************************************************
host.example.org : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by jankowa** [comment]
i just could reproduce it with a fresh upgraded server (bullseye to buster) without the debops builtin dist-upgrade tool. After upgrading manually to bullseye debops fails with the same error.

**Comment by jankowa** [comment]
ok, responsible is the wrong python interpreter in the fact files: python3.7 which doesn't exists any more on bullseye 
```
cd /etc/ansible/facts.d
for i in *; do sed -i 's|^#!/usr/bin/python3.7|#!/usr/bin/python3.9|g' $i; done
```
solves it so far. But next error is:

```
TASK [debops.debops.python : Install requested packages] *********************************************************************************************
fatal: [example.org]: FAILED! => changed=false 
  attempts: 3
  msg: No package matching 'python-apt' is available
```

Removing `/etc/ansible/facts.d/python.fact` solves it.

**Comment by R053NR07** [comment]
Hey,
we have the same issue here and the sed command + python.fact deletion from https://github.com/debops/debops/issues/2149#issuecomment-1256635491 helped at first. Somehow the facts broke after that again. Running bootstrap again triggered debops.debops.core which seemed to change the distribution release in the facts; not sure if this circumvents the problem in the future but currently the fact generation does not break again.
