### ISSUE TITLE
debops.lvm:  string issue

### ISSUE THREAD

**Issue by stefangweichinger** [debops/debops#2361]
```
TASK [debops.debops.lvm : Configure LVM] **********************************************************************************************************************
task path: /home/sgw/.local/lib/python3.11/site-packages/debops/_data/ansible/collections/ansible_collections/debops/debops/roles/lvm/tasks/main.yml:37
The full traceback is:
Traceback (most recent call last):
  File "/home/sgw/.local/lib/python3.11/site-packages/ansible/template/__init__.py", line 987, in do_template
    res = self.environment.concat(rf)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sgw/.local/lib/python3.11/site-packages/ansible/template/native_helpers.py", line 83, in ansible_concat
    return ''.join([to_text(v) for v in nodes])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sgw/.local/lib/python3.11/site-packages/ansible/template/native_helpers.py", line 83, in <listcomp>
    return ''.join([to_text(v) for v in nodes])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 239, in root
  File "/usr/lib/python3.11/site-packages/jinja2/runtime.py", line 349, in call
    return __obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/jinja2/runtime.py", line 814, in __call__
    return self._invoke(arguments, autoescape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/jinja2/runtime.py", line 828, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 200, in macro
  File "/usr/lib/python3.11/site-packages/jinja2/runtime.py", line 349, in call
    return __obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/jinja2/runtime.py", line 814, in __call__
    return self._invoke(arguments, autoescape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/jinja2/runtime.py", line 828, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 157, in macro
TypeError: sequence item 2: expected str instance, int found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sgw/.local/lib/python3.11/site-packages/ansible/plugins/action/template.py", line 141, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sgw/.local/lib/python3.11/site-packages/ansible/template/__init__.py", line 998, in do_template
    raise AnsibleError("Unexpected templating type error occurred on (%s): %s" % (to_native(data), to_native(te)), orig_exc=te)
ansible.errors.AnsibleError: Unexpected templating type error occurred on ({# Copyright (C) 2015-2016 Maciej Delmanowski <drybjed@gmail.com>
 # Copyright (C) 2015-2016 DebOps <https://debops.org/>
 # SPDX-License-Identifier: GPL-3.0-only
 #}
# {{ ansible_managed }}

{% if lvm__config_base_version | d() %}
# lvm.conf based on lvm2 package version: {{ lvm__config_base_version }}

{% endif %}
{% set lvm__tpl_base = lvm__config_base %}
{% set lvm__tpl_config = lvm__config %}
{% macro print_content (key, value) %}
{% if value is not iterable %}
{% if value in [ 0, 1 ] %}
{% if value | bool %}
{{ key }} = 1
{% elif not value | bool %}
{{ key }} = 0
{% endif %}
{% elif value is number %}
{{ key }} = {{ value }}
{% endif %}
{% elif value is iterable %}
{% if value is string %}
{% if value[0:1] == "0" %}
{{ key }} = {{ value }}
{% else %}
{{ key }} = "{{ value }}"
{% endif %}
{% else %}
{% if value | length > 0 %}
{{ key }} = [ "{{ value | join('", "') }}" ]
{% else %}
{{ key }} = [ ]
{% endif %}
{% endif %}
{% endif %}
{% endmacro %}
{% macro print_section (name, content, mask) %}
{%   set seen_keys = [] %}
{{ name }} {
{%   for key, value in content.items() %}
{%     if value is mapping %}
{{ print_section (key, value, {}) | indent (4,true) }}
{%       set _ = seen_keys.append(key) %}
{%     else %}
{%       if key in mask.keys() %}
{{ print_content (key, mask[key]) | indent (4,true) }}
{%         set _ = seen_keys.append(key) %}
{%       else %}
{{ print_content (key, value) | indent (4,true) }}
{%         set _ = seen_keys.append(key) %}
{%       endif %}
{%     endif %}
{%   endfor %}
{%   if mask %}
{%     for key, value in mask.items() %}
{%       if key not in seen_keys %}
{{ print_content ( key, value) | indent (4,true) }}
{%       endif %}
{%     endfor %}
{%   endif %}
}
{% endmacro %}
{% set seen_sections = [] %}
{% for section in lvm__tpl_base.keys() | sort %}
{% if section in lvm__tpl_config.keys() %}
{{ print_section (section, lvm__tpl_base[section], lvm__tpl_config[section]) }}
{% set _ = seen_sections.append(section) %}
{% else %}
{{ print_section (section, lvm__tpl_base[section], {}) }}
{% set _ = seen_sections.append(section) %}
{% endif %}
{% endfor %}
{% for section in lvm__tpl_config.keys() | sort %}
{% if section not in seen_sections %}
{{ print_section (section, lvm__tpl_config[section], {}) }}
{% endif %}
{% endfor %}
): sequence item 2: expected str instance, int found. sequence item 2: expected str instance, int found
fatal: [morgan]: FAILED! => changed=false 
  msg: |-
    AnsibleError: Unexpected templating type error occurred on ({# Copyright (C) 2015-2016 Maciej Delmanowski <drybjed@gmail.com>
     # Copyright (C) 2015-2016 DebOps <https://debops.org/>
     # SPDX-License-Identifier: GPL-3.0-only
     #}
    # {{ ansible_managed }}
  
    {% if lvm__config_base_version | d() %}
    # lvm.conf based on lvm2 package version: {{ lvm__config_base_version }}
  
    {% endif %}
    {% set lvm__tpl_base = lvm__config_base %}
    {% set lvm__tpl_config = lvm__config %}
    {% macro print_content (key, value) %}
    {% if value is not iterable %}
    {% if value in [ 0, 1 ] %}
    {% if value | bool %}
    {{ key }} = 1
    {% elif not value | bool %}
    {{ key }} = 0
    {% endif %}
    {% elif value is number %}
    {{ key }} = {{ value }}
    {% endif %}
    {% elif value is iterable %}
    {% if value is string %}
    {% if value[0:1] == "0" %}
    {{ key }} = {{ value }}
    {% else %}
    {{ key }} = "{{ value }}"
    {% endif %}
    {% else %}
    {% if value | length > 0 %}
    {{ key }} = [ "{{ value | join('", "') }}" ]
    {% else %}
    {{ key }} = [ ]
    {% endif %}
    {% endif %}
    {% endif %}
    {% endmacro %}
    {% macro print_section (name, content, mask) %}
    {%   set seen_keys = [] %}
    {{ name }} {
    {%   for key, value in content.items() %}
    {%     if value is mapping %}
    {{ print_section (key, value, {}) | indent (4,true) }}
    {%       set _ = seen_keys.append(key) %}
    {%     else %}
    {%       if key in mask.keys() %}
    {{ print_content (key, mask[key]) | indent (4,true) }}
    {%         set _ = seen_keys.append(key) %}
    {%       else %}
    {{ print_content (key, value) | indent (4,true) }}
    {%         set _ = seen_keys.append(key) %}
    {%       endif %}
    {%     endif %}
    {%   endfor %}
    {%   if mask %}
    {%     for key, value in mask.items() %}
    {%       if key not in seen_keys %}
    {{ print_content ( key, value) | indent (4,true) }}
    {%       endif %}
    {%     endfor %}
    {%   endif %}
    }
    {% endmacro %}
    {% set seen_sections = [] %}
    {% for section in lvm__tpl_base.keys() | sort %}
    {% if section in lvm__tpl_config.keys() %}
    {{ print_section (section, lvm__tpl_base[section], lvm__tpl_config[section]) }}
    {% set _ = seen_sections.append(section) %}
    {% else %}
    {{ print_section (section, lvm__tpl_base[section], {}) }}
    {% set _ = seen_sections.append(section) %}
    {% endif %}
    {% endfor %}
    {% for section in lvm__tpl_config.keys() | sort %}
    {% if section not in seen_sections %}
    {{ print_section (section, lvm__tpl_config[section], {}) }}
    {% endif %}
    {% endfor %}
    ): sequence item 2: expected str instance, int found. sequence item 2: expected str instance, int found
```

Looks similar to https://github.com/debops/debops/pull/2212 to me. Although I don't yet "see" the fix ;-)

**Comment by stefangweichinger** [comment]
fixed by upgrading Jinja2 

```
pip install -U Jinja2
```

(Fedora 38 Workstation)
