### ISSUE TITLE
"name 'unicode' is not defined" in debops_filter_plugins -> _parse_kv_value

### ISSUE THREAD

**Issue by jankatins** [debops/debops#256]
TASK [debops.sysctl : Remove sysctl configuration files if requested] ********************************************************************************************************************************
task path: /home/js/.local/share/debops/debops/ansible/roles/debops.sysctl/tasks/main.yml:33
The full traceback is:
Traceback (most recent call last):
  File "/home/js/.binaries/miniconda3/lib/python3.5/site-packages/ansible/executor/task_executor.py", line 88, in run
    items = self._get_loop_items()
  File "/home/js/.binaries/miniconda3/lib/python3.5/site-packages/ansible/executor/task_executor.py", line 207, in _get_loop_items
    convert_bare=False)
  File "/home/js/.binaries/miniconda3/lib/python3.5/site-packages/ansible/utils/listify.py", line 34, in listify_lookup_plugin_terms
    terms = templar.template(terms.strip(), convert_bare=convert_bare, fail_on_undefined=fail_on_undefined)
  File "/home/js/.binaries/miniconda3/lib/python3.5/site-packages/ansible/template/__init__.py", line 450, in template
    disable_lookups=disable_lookups,
  File "/home/js/.binaries/miniconda3/lib/python3.5/site-packages/ansible/template/__init__.py", line 672, in do_template
    res = j2_concat(rf)
  File "<template>", line 12, in root
  File "/home/js/.local/share/debops/debops/ansible/roles/debops.ansible_plugins/filter_plugins/debops_filter_plugins.py", line 347, in parse_kv_items
    current_options + element.get('options'))
  File "/home/js/.local/share/debops/debops/ansible/roles/debops.ansible_plugins/filter_plugins/debops_filter_plugins.py", line 191, in parse_kv_config
    current_param.get('id'))
  File "/home/js/.local/share/debops/debops/ansible/roles/debops.ansible_plugins/filter_plugins/debops_filter_plugins.py", line 39, in _parse_kv_value
    if isinstance(new_value, (str, unicode, int, float, bool)):
NameError: name 'unicode' is not defined

**Comment by drybjed** [comment]
What Python version are you using with Ansible?

**Comment by jankatins** [comment]
py3

It's probably enough to do something like this at the top of the [file](https://github.com/debops/debops/blob/master/ansible/roles/debops.ansible_plugins/filter_plugins/debops_filter_plugins.py)

```py
try:
    unicode = unicode
except:
    # py3
    unicode = str
```

**Comment by drybjed** [comment]
Can you check if that fixes the issue? I'll try it out on my end ASAP.

**Comment by jankatins** [comment]
currently trying it :-) Let's see..

**Comment by drybjed** [comment]
Looks like it works fine with Python 2.7.

**Comment by jankatins** [comment]
Yep, works on py3

**Comment by jankatins** [comment]
Used this:

```python
try:
    unicode = unicode
except NameError:
    # py3
    unicode = str
```

**Comment by drybjed** [comment]
Great, thanks. I'll fix this with the next patch then.

**Comment by drybjed** [comment]
This issue should be fixed by https://github.com/debops/debops/pull/257/commits/23ff21134c9b52abf344f3246244eecea1d53ef6.

**Comment by jankatins** [comment]
It's not an `ImportError`, it's a `NameError`.

**Comment by drybjed** [comment]
Ah, sorry, my bad. I see now that it's not an import, will fix ASAP.

**Comment by drybjed** [comment]
@jankatins Does it work now, with https://github.com/debops/debops/pull/258?

**Comment by jankatins** [comment]
yes
