### ISSUE TITLE
error while use debops.sshd as standalone  role

### ISSUE THREAD

**Issue by alex-tu-cc** [debops/debops#378]
[from document, all rule should can be used standalone ](https://docs.debops.org/en/master/introduction/faq.html#can-i-use-debops-roles-as-standalone)

But in lookup plugin template_src.py which is used across lots of roles, it assume the executed root is under debops project folder, so all those roles will not able to be used standalone in playbook without under debops project folder.

error message:
TASK [debops.sshd : Setup /etc/ssh/sshd_config] **********************************************************************
task path: /home/alextu/my-library/github/ansible/roles/debops.sshd/tasks/main.yml:108                               
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 138, in run                        
    res = self._execute()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 506, in _execute                   
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/task.py", line 260, in post_validate                       
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/base.py", line 390, in post_validate                       
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 525, in template                        
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 481, in template                        
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 717, in do_template                     
    res = j2_concat(rf)
  File "<template>", line 11, in root
  File "/usr/lib/python2.7/dist-packages/jinja2/runtime.py", line 262, in call                                       
    return __obj(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 615, in _lookup                         
    instance = self._lookup_loader.get(name.lower(), loader=self._loader, templar=self)                              
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/loader.py", line 366, in get                                
    self._module_cache[path] = self._load_module_source(name, path)                                                  
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/loader.py", line 345, in _load_module_source                
    module = imp.load_source(full_name, path, module_file)
  File "/home/alextu/my-library/github/ansible/debops/ansible/playbooks/lookup_plugins/template_src.py", line 23, in <module>
    from debops import *
ImportError: No module named debops

fatal: [node1]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}

**Comment by drybjed** [comment]
DebOps uses a few custom Ansible plugins to provide additional functionality inside of the roles without the need to modify them. These plugins use code included in the `debops` Python module to read the `.debops.cfg` configuration file and get the configuration from it.

I would like to remove the need to use these custom `*_src` plugins, but this requires that the roles support the functionality offered by them in a different way, which means a bit of the redesign. This will be done some time in the future, right now my focus is elsewhere.

**Comment by drybjed** [comment]
The custom lookup plugins are now part of the `debops.ansible_plugins` role which the `debops.sshd` role depends on. This issue should not happen anymore, so I'm closing it as resolved.
