### ISSUE TITLE
[debops.gunicorn] ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by mikenowak** [debops/debops#491]
I am seeing this error while trying to deploy netbox

```
Failed to read config file: /etc/gunicorn/netbox.conf.py
Traceback (most recent call last):
  File "/usr/local/lib/netbox/virtualenv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 93, in get_config_from_filename
    execfile_(filename, cfg, cfg)
  File "/usr/local/lib/netbox/virtualenv/local/lib/python2.7/site-packages/gunicorn/_compat.py", line 91, in execfile_
    return execfile(fname, *args)
  File "/etc/gunicorn/netbox.conf.py", line 95, in <module>
    spew = loads("""False""")
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

This is on bionic (ubuntu 18.04) with gunicorn 19.7.1-4.

It turns out that gunicorn doesn't like the following lines in the ***application.conf.py***.

```
spew = loads("""False""")
daemon = loads("""False""")
tmp_upload_dir = loads("""None""")
remote_header = loads("""X-Real-IP""")
proc_name = loads("""None""")
```

Commenting them out allows the gunicorn start normally.

**Comment by drybjed** [comment]
Hmm, this wrapping was done due to `pycodestyle` complaining about weird stuff in a Python script. Perhaps the `gunicorn` configuration template should be ignored during tests, in which case the wrap for Jinja code wouldn't be needed. I'll fix this in the next few days.

**Comment by mikenowak** [comment]
@drybjed, confirmed - this is now working as intended - many thanks
