### ISSUE TITLE
[debops.netbox] migrating to python3

### ISSUE THREAD

**Issue by mikenowak** [debops/debops#580]
As per the https://netbox.readthedocs.io/en/latest/installation/migrating-to-python3/, starting with netbox v2.5, netbox no longer supports python 2.

This prevents netbox from starting at the moment since we default to `netbox__git_version: 'master'`

I don't really have the capacity to work on this at the moment, but in case somebody needs to revert to a working version, the following needs to be adjusted as follows:

```
netbox__git_version: 'v2.4.9'
```

**Comment by drybjed** [comment]
@mikenowak Thanks for the bug report. I'm aware of the issue with NetBox, hadn't had an opportunity to test some kind of transition yet, but I'm planning on doing so.

I'm not sure how to approach this yet. Probably going "straight" and just switching to Py3 `virtualenv` in the role would leave existing installations broken and require a clean reinstall of NetBox, so I don't really want to do that. Role would probably have to check if existing py2 `virtualenv` is set up and then do migration to py3 `virtualenv`. I'm not sure yet if existing virtual environments can be upgraded, or you should just create a new `virtualenv` with py3 and install NetBox there as usual - that probably could work, depending on the role checking if an existing database is set up and not clobbering it.

In the meantime, perhaps DebOps should switch to the NetBox version you specified. Then I can release a new DebOps v0.8.1 which I'm planning to do before New Years hits, and after that we can research some kind of migration steps. What do you think about this? Want to do a PR to change the default version of NetBox for now?

**Comment by mikenowak** [comment]
hi @drybjed, I totally agree and I am also worried about leaving garbage behind as part of this upgrade.

In the meantime, please see the PR as requested.

**Comment by mikenowak** [comment]
my bad, wasnt meant to close this one.

**Comment by drybjed** [comment]
@mikenowak Can you check if recent changes in `debops.netbox` solve this issue for you?

**Comment by mikenowak** [comment]
While I acknowledge that the new virtualenv has been installed, and old removed, it quite did not solve the issue. 

```
Jan 09 01:42:24 web1 systemd[1]: Started Green Unicorn - Python application server for netbox.
Jan 09 01:42:24 web1 gunicorn@netbox[2761]: Traceback (most recent call last):
Jan 09 01:42:24 web1 gunicorn@netbox[2761]:   File "/usr/bin/gunicorn3", line 6, in <module>
Jan 09 01:42:24 web1 gunicorn@netbox[2761]:     from pkg_resources import load_entry_point
Jan 09 01:42:24 web1 gunicorn@netbox[2761]:   File "/usr/local/lib/netbox/virtualenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in <module>
Jan 09 01:42:24 web1 gunicorn@netbox[2761]:     @_call_aside
Jan 09 01:42:24 web1 gunicorn@netbox[2761]:   File "/usr/local/lib/netbox/virtualenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
Jan 09 01:42:24 web1 gunicorn@netbox[2761]:     f(*args, **kwargs)
Jan 09 01:42:24 web1 gunicorn@netbox[2761]:   File "/usr/local/lib/netbox/virtualenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3139, in _initialize
Jan 09 01:42:24 web1 gunicorn@netbox[2761]:     working_set = WorkingSet._build_master()
Jan 09 01:42:24 web1 gunicorn@netbox[2761]:   File "/usr/local/lib/netbox/virtualenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 581, in _build_maste
Jan 09 01:42:24 web1 gunicorn@netbox[2761]:     ws.require(__requires__)
Jan 09 01:42:24 web1 gunicorn@netbox[2761]:   File "/usr/local/lib/netbox/virtualenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 898, in require
Jan 09 01:42:24 web1 gunicorn@netbox[2761]:     needed = self.resolve(parse_requirements(requirements))
Jan 09 01:42:24 web1 gunicorn@netbox[2761]:   File "/usr/local/lib/netbox/virtualenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 784, in resolve
Jan 09 01:42:24 web1 gunicorn@netbox[2761]:     raise DistributionNotFound(req, requirers)
Jan 09 01:42:24 web1 gunicorn@netbox[2761]: pkg_resources.DistributionNotFound: The 'gunicorn==19.7.1' distribution was not found and is required by the application
Jan 09 01:42:24 web1 systemd[1]: gunicorn@netbox.service: Main process exited, code=exited, status=1/FAILURE
Jan 09 01:42:24 web1 systemd[1]: gunicorn@netbox.service: Failed with result 'exit-code'.
```

The following are installed

```
ii  gunicorn                        19.7.1-4                                    all          Event-based HTTP/WSGI server (Python 2 version)
ii  gunicorn3                       19.7.1-4                                    all          Event-based HTTP/WSGI server (Python 3 version)
ii  python-gunicorn                 19.7.1-4                                    all          Event-based HTTP/WSGI server (Python 2 libraries)
ii  python3-gunicorn                19.7.1-4                                    all          Event-based HTTP/WSGI server (Python 3 libraries)
```

**Comment by drybjed** [comment]
That's probably required when you use `gunicorn3` inside of the `virtualenv`, depending on the value of `netbox__app_internal_appserver` variable. Can you check if `gunicorn` Python module is installed in the virtualenv of NetBox?

What happens if you remove `/usr/local/lib/netbox/virtualenv/` and re-run the role? It should recreate and re-install everything, database and media files should be preserved (do you have backups?).

**Comment by mikenowak** [comment]
OK, I had a look and I believe that the following is meant to install the same version of unicorn in the virtualenv that is installed on the OS 

```
netbox__virtualenv_pip_packages:
  - name: 'gunicorn'
    version: '{{ ansible_local.gunicorn.version
                 if (ansible_local|d() and ansible_local.gunicorn|d() and
                     ansible_local.gunicorn.version|d())
                 else omit }}'
```

So I removed the virtualenv dir, re-ran the role but that still doesn't appear to be installed.

So I've installed that manually for the moment, and netbox app had started.

```
$ sudo -H -u netbox bash
$ cd /usr/local/lib/netbox/virtualenv
$ . ./bin/activate
(virtualenv) netbox@web1:/usr/local/lib/netbox/virtualenv$ pip list
Package                  Version   
------------------------ ----------
------------------------ ----------
certifi                  2018.11.29
chardet                  3.0.4     
click                    6.7       
coreapi                  2.3.3     
coreschema               0.0.4     
Django                   2.1.4     
django-auth-ldap         1.7.0     
django-cors-headers      2.4.0     
django-debug-toolbar     1.11      
django-filter            2.0.0     
django-js-asset          1.1.0     
django-mptt              0.9.1     
django-tables2           2.0.3     
django-taggit            0.23.0    
django-taggit-serializer 0.1.7     
django-timezone-field    3.0       
djangorestframework      3.9.0     
drf-yasg                 1.11.1    
flex                     6.13.2    
graphviz                 0.10.1    
idna                     2.8       
inflection               0.3.1     
itypes                   1.1.0     
Jinja2                   2.10      
jsonpointer              1.14      
jsonschema               2.6.0     
Markdown                 2.6.11    
MarkupSafe               1.1.0     
netaddr                  0.7.19    
Pillow                   5.3.0     
pip                      18.1      
pkg-resources            0.0.0     
psycopg2-binary          2.7.6.1   
py-gfm                   0.1.4     
pyasn1                   0.4.5     
pyasn1-modules           0.2.3     
pycryptodome             3.7.2     
python-ldap              3.1.0     
pytz                     2018.9    
PyYAML                   3.13      
requests                 2.21.0    
rfc3987                  1.3.8     
ruamel.yaml              0.15.85   
setuptools               40.6.3    
six                      1.12.0    
sqlparse                 0.2.4     
strict-rfc3339           0.7       
swagger-spec-validator   2.4.1     
uritemplate              3.0.0     
urllib3                  1.24.1    
validate-email           1.3       
wheel                    0.32.3 
(virtualenv) netbox@web1:/usr/local/lib/netbox/virtualenv$ pip install gunicorn==19.7.1

Collecting gunicorn==19.7.1
  Using cached https://files.pythonhosted.org/packages/64/32/becbd4089a4c06f0f9f538a76e9fe0b19a08f010bcb47dcdbfbc640cdf7d/gunicorn-19.7.1-py2.py3-none-any.whl
Installing collected packages: gunicorn
Successfully installed gunicorn-19.7.1
```
