### ISSUE TITLE
[debops.libvirtd] Unsupported facts with Python3

### ISSUE THREAD

**Issue by nqb** [debops/debops#881]
Hello,

I noticed following issue when running `libvirt.fact` with Python 3:

```console
# python3 libvirtd.fact
Traceback (most recent call last):
  File "libvirtd.fact", line 44, in <module>
    print(dumps(output, sort_keys=True, indent=2))
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'3.0.0' is not JSON serializable
```

I'm sure it's really easy to fix but didn't find the time to work on it.

@htgoebel, a job for you ? :-)

**Comment by nqb** [comment]
Need to be tested but #919 should fixed it.

**Comment by drybjed** [comment]
The bug has been fixed, closing.
